# Generated by Django 5.1.3 on 2024-11-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_sub_category_alter_productorder_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
