# Generated by Django 5.1.3 on 2024-12-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartorder_return_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='return_request_status',
            field=models.CharField(choices=[('New', 'New'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Failed', 'Failed')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Payment Pending', 'Payment Pending'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
