# Generated by Django 5.1.4 on 2024-12-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cartorder_return_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productattribute'),
        ),
    ]
