# Generated by Django 5.1.4 on 2024-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_categoryoffer_is_active_productoffer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount in percentage'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount in percentage'),
        ),
    ]
